version: '3'
services:
  app:
    # image: learn4img
    # Path to dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # links:
    #   - mongo
    #   - redis
    # depends_on:
    #   - mongo
    #   - redis
    # environment:
    #   - MONGO_URL=mongodb://mongo/evolveProd
    #   - REDIS_HOST=redis
    # networks:
    #   - evolve